apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: UdviklerPortal
  description: The place to be, for great
  labels:
    example.com/custom: custom_label_value
  annotations:
    example.com/service-discovery: web
    circleci.com/project-slug: github/example-org/website
  tags:
    - java
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
spec:
  type: website
  lifecycle: production
  owner: backstage-team
  system: backstage
