apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: UFST
  description: Udvikling og Forenklingsstyrelsen
spec:
  type: ops
  profile:
    displayName: Udvikling og Forenklingsstyrelsen
  children: [backstage-team]
  members: [frank, lars, morten]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: UdviklerPortal
  description: The place to be, for great
  labels:
    example.com/custom: custom_label_value
  annotations:
    example.com/service-discovery: web
    circleci.com/project-slug: github/example-org/website
  tags:
    - java
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
spec:
  type: website
  lifecycle: production
  owner: backstage-team
  system: backstage
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: Tooling
  description: Software Development & Continuous Integration & Continuous Delivery Pipelines
  tags:
    - depops
spec:
  owner: backstage-team
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage-team
  description: The backstage-team
spec:
  type: team
  profile:
    displayName: Udvikling Kernefunktionalitet
    email: infrastructure@ufst.dk
  parent: ops 
  children: [backstage, other]
  members: [frank, lars]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: frank.vilhelmsen
spec:
  profile:
    email: frank.vilhelmsen@ufst.dk
  memberOf: [backstage-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: lars.nymand
spec:
  profile:
    email: lars.jensen@ufst.dk
  memberOf: [backstage-team]
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backstage
  description: An open platform for building developer portals
spec:
  owner: backstage-team
  domain: Tooling
