apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: org-data
spec:
  type: url
  targets:
    - http://github.com/myorg/myproject/org-data-dump/catalog-info-staff.yaml
    - https://github.com/frankvilhelmsen/dokumentations-template/blob/master/catalog-info-component.yaml
