apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: Tooling
  description: Software Development & Continuous Integration & Continuous Delivery Pipelines
  tags:
    - depops
spec:
  owner: backstage-team
