apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Business-Unit
spec:
  type: business-unit
  profile:
    displayName: business-unit 
  parent: 
  children: [backstage-team]
  members: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage-team
  description: The backstage-team
spec:
  type: team
  profile:
    displayName: Udvikling Kernefunktionalitet
    email: infrastructure@ufst.dk
  parent: infrastructure
  children: [backstage, other]
  members: [frank, lars]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: frank.vilhelmsen
spec:
  profile:
    email: frank.vilhelmsen@ufst.dk
  memberOf: [backstage-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: lars.nymand
spec:
  profile:
    email: lars.jensen@ufst.dk
  memberOf: [backstage-team]
  
