apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: relations-team
  description: The infra business unit
spec:
  type: team
  profile:
    displayName: Infrastructure
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: ops
  children: [backstage, other]
  members: [frank, lars]
  
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: frank.vilhelmsen
spec:
  profile:
    email: frankvilhelmse@ufst.dk
  memberOf: [relations-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: lars.nymand
spec:
  profile:
    email: lars-nymand@ufst.dk
  memberOf: [relations-team]
  
