apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: dokumentations-template
  title: Dokumentations Template
  description: Laver et nyt dokumentations project
  tags:
    - recommended
    - techdocs
    - mkdocs
spec:
  owner: backstage/techdocs-core
  type: documentation

  parameters:
    - title: Udfyld trin
      required:
        - name
        - description
      properties:
        name:
          title: Name
          type: string
          description: Unique navn på komponent
          ui:autofocus: true
          ui:options:
            rows: 5
        description:
          title: Description
          type: string
          description: Beskrivelse af komponent
          ui:autofocus: true
          ui:options:
            rows: 5

  # This template is meant to be used on top of an existing tmeplate.
  # By adding the following and fetching from an absolute URL you can 
  # add in the docs template
  steps:
    - id: fetch
      name: Template Docs Skeleton
      action: fetch:cookiecutter
      input:
        url: ./skeleton
        values:
          name: '{{ parameters.name }}'
          description: '{{ parameters.description }}'
